apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: billing-service-base

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - hpa.yaml

commonLabels:
  app: billing-service
  component: microservice
  version: v1