apiVersion: v1
kind: Service
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  selector:
    app: billing-service
  ports:
  - name: http
    port: 8007
    targetPort: 8007
    protocol: TCP
  type: ClusterIP