apiVersion: v1
kind: Service
metadata:
  name: eval-service
  labels:
    app: eval-service
spec:
  selector:
    app: eval-service
  ports:
  - name: http
    port: 8011
    targetPort: 8011
    protocol: TCP
  type: ClusterIP