apiVersion: v1
kind: Service
metadata:
  name: router-service
  labels:
    app: router-service
spec:
  selector:
    app: router-service
  ports:
  - name: http
    port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP