apiVersion: v1
kind: Service
metadata:
  name: chat-adapters-service
spec:
  selector:
    app: chat-adapters-service
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      name: http
