apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: admin-portal-dev

namespace: multi-ai-agent-dev

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

configMapGenerator:
  - name: admin-portal-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=DEBUG