apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  labels:
    app: admin-portal
spec:
  selector:
    app: admin-portal
  ports:
  - name: http
    port: 8100
    targetPort: 8100
    protocol: TCP
  type: ClusterIP