apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: semantic-cache-service
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: semantic-cache-service
