apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacity-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capacity-monitor
  template:
    metadata:
      labels:
        app: capacity-monitor
    spec:
      containers:
      - name: capacity-monitor
        image: capacity-monitor:IMAGE_TAG
        ports:
        - containerPort: 8012
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        envFrom:
        - configMapRef:
            name: capacity-monitor-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8012
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8012
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"