name: mcp-rag-ci
on:
  push:
    branches: [main]
    paths: ["apps/mcp-rag/**"]
  pull_request:
    paths: ["apps/mcp-rag/**"]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mcp-rag
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: pytest -q
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mcp-rag
    steps:
      - uses: actions/checkout@v4
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: apps/mcp-rag
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mcp-rag:${{ github.sha }}
      - name: Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/mcp-rag:${{ github.sha }}

