apiVersion: v1
kind: Service
metadata:
  name: feature-flags-service
spec:
  selector:
    app: feature-flags-service
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      name: http
