openapi: 3.0.3
info: { title: model-gateway, version: "0.1.0" }
paths:
  /healthz: { get: { responses: { "200": { description: ok } } } }
  /v1/chat:
    post:
      requestBody:
        {
          required: true,
          content: { application/json: { schema: { type: object } } },
        }
      responses: { "200": { description: ok } }
  /v1/embeddings:
    post:
      requestBody:
        {
          required: true,
          content: { application/json: { schema: { type: object } } },
        }
      responses: { "200": { description: ok } }
