openapi: 3.0.3
info: { title: config-service, version: "0.1.0" }
paths:
  /healthz: { get: { responses: { "200": { description: ok } } } }
  /v1/config:
    get:
      parameters:
        - in: query; name: env; schema: { type: string, default: production }
        - in: query; name: key; schema: { type: string }
      responses: { "200": { description: ok } }
    post:
      requestBody:
        required: true
        content: { application/json: { schema: { type: object, required: [env,key,value], properties:
          { env: {type: string}, key: {type: string}, value: {} } } } }
      responses: { "200": { description: ok } }

