apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: notification-service
