apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
  - name: http
    port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP