apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: api-gateway-base

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - hpa.yaml

commonLabels:
  app: api-gateway
  component: microservice
  version: v1