image:
  repository: ghcr.io/OWNER/api-gateway
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  port: 8080
resources:
  limits: { cpu: 300m, memory: 256Mi }
  requests: { cpu: 50m, memory: 128Mi }
env: []
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
pdb: { minAvailable: 1 }
