apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-adapters
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-adapters
  template:
    metadata:
      labels:
        app: chat-adapters
    spec:
      containers:
      - name: chat-adapters
        image: chat-adapters:IMAGE_TAG
        ports:
        - containerPort: 8009
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        envFrom:
        - configMapRef:
            name: chat-adapters-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"