openapi: 3.0.3
info:
  title: Chat Adapters Service
  description: Multi-channel chat integration
  version: 1.0.0
  contact:
    name: Platform Team
    email: platform@company.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: http://localhost:8009
  description: Development server
- url: https://api.company.com
  description: Production server
security:
- BearerAuth: []
paths:
  /healthz:
    get:
      summary: Health check endpoint
      operationId: health_check
      tags:
      - Health
      security: []
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /v1/info:
    get:
      summary: Service information
      operationId: get_info
      tags:
      - Info
      security: []
      responses:
        '200':
          description: Service information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
  /v1/adapters:
    get:
      summary: List chat adapters
      operationId: get__v1_adapters
      tags:
      - Chat Adapters
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/adapters/{adapter}/send:
    post:
      summary: Send message via adapter
      operationId: post__v1_adapters_adapter_send
      tags:
      - Chat Adapters
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
  /v1/adapters/{adapter}/webhook:
    post:
      summary: Handle webhook
      operationId: post__v1_adapters_adapter_webhook
      tags:
      - Chat Adapters
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
  /v1/conversations/{conversation_id}/messages:
    get:
      summary: Get messages
      operationId: get__v1_conversations_conversation_id_messages
      tags:
      - Chat Adapters
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    HealthResponse:
      type: object
      required:
      - status
      - timestamp
      properties:
        status:
          type: string
          enum:
          - healthy
          - degraded
          - unhealthy
        timestamp:
          type: string
          format: date-time
        version:
          type: string
        components:
          type: object
          additionalProperties:
            type: string
    InfoResponse:
      type: object
      required:
      - service
      - version
      properties:
        service:
          type: string
          example: chat-adapters
        version:
          type: string
          example: 1.0.0
        description:
          type: string
          example: Multi-channel chat integration
        build_time:
          type: string
          format: date-time
        commit_sha:
          type: string
    ErrorResponse:
      type: object
      required:
      - error
      - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
        trace_id:
          type: string
