apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: aiaas
  labels:
    app: orchestrator
    version: v2.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        version: v2.0.0
    spec:
      containers:
        - name: orchestrator
          image: multi-ai-agent/orchestrator:latest
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: url
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: nats-secrets
                  key: url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secrets
                  key: api-key
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: aiaas
  labels:
    app: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orchestrator-hpa
  namespace: aiaas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orchestrator
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: orchestrator-keda
  namespace: aiaas
spec:
  scaleTargetRef:
    name: orchestrator
  minReplicaCount: 2
  maxReplicaCount: 20
  triggers:
    - type: nats
      metadata:
        natsServerMonitoringEndpoint: "nats:8222"
        queueGroup: "orchestrator"
        queueSubject: "agent.run.requested"
        lagThreshold: "5"
