apiVersion: v1
kind: Service
metadata:
  name: tool-service
  labels:
    app: tool-service
spec:
  selector:
    app: tool-service
  ports:
  - name: http
    port: 8010
    targetPort: 8010
    protocol: TCP
  type: ClusterIP