apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  selector:
    app: ingestion
  ports:
  - name: http
    port: 8006
    targetPort: 8006
    protocol: TCP
  type: ClusterIP