openapi: 3.0.3
info:
  title: Shared Platform Schemas
  description: Common schemas and types used across multiple services
  version: 1.0.0
components:
  schemas:
    TenantContext:
      type: object
      required:
      - tenant_id
      - plan_tier
      properties:
        tenant_id:
          type: string
          format: uuid
          description: Unique tenant identifier
        plan_tier:
          type: string
          enum:
          - free
          - pro
          - enterprise
          description: Tenant subscription tier
        region:
          type: string
          description: Geographic region
        features:
          type: array
          items:
            type: string
          description: Enabled features for this tenant
    ErrorResponse:
      type: object
      required:
      - error
      - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details
        trace_id:
          type: string
          description: Request trace identifier
    PaginationRequest:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
          default: 1
          description: Page number
        limit:
          type: integer
          minimum: 1
          maximum: 100
          default: 20
          description: Items per page
        sort:
          type: string
          description: Sort field and direction (e.g., 'created_at:desc')
    PaginationResponse:
      type: object
      required:
      - total
      - page
      - limit
      - pages
      properties:
        total:
          type: integer
          description: Total number of items
        page:
          type: integer
          description: Current page number
        limit:
          type: integer
          description: Items per page
        pages:
          type: integer
          description: Total number of pages
    AuditMetadata:
      type: object
      required:
      - created_at
      - created_by
      properties:
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        created_by:
          type: string
          description: User who created the resource
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
        updated_by:
          type: string
          description: User who last updated the resource
