openapi: 3.0.3
info: { title: audit-log, version: "0.1.0" }
paths:
  /healthz: { get: { responses: { "200": { description: ok } } } }
  /v1/audit:
    post:
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: "#/components/schemas/AuditEvent" } } }
      responses: { "200": { description: ok } }
    get:
      parameters:
        - in: query; name: tenant_id; schema: { type: string }
        - in: query; name: actor; schema: { type: string }
        - in: query; name: resource; schema: { type: string }
      responses: { "200": { description: ok } }
components:
  schemas:
    AuditEvent:
      type: object
      required: [tenant_id, actor, action, resource]
      properties:
        tenant_id: { type: string }
        actor: { type: string }
        action: { type: string }
        resource: { type: string }
        meta: { type: object, additionalProperties: true }
        ts: { type: string, format: date-time }

