name: "Tenant Service CI/CD"

on:
  push:
    paths:
      - "apps/tenant-service/**"
      - "libs/**"
      - "contracts/**"
      - "platform/ci-templates/**"
      - ".github/workflows/tenant-service-*.yaml"
  pull_request:
    paths:
      - "apps/tenant-service/**"
      - "libs/**"
      - "contracts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: "Build and Test Tenant Service"
    uses: ./platform/ci-templates/service-ci.yaml
    with:
      language: "python"
      service_path: "apps/tenant-service"
      service_name: "tenant-service"
      enable_docker: true
      enable_sbom: true
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # Optional: Service-specific deployment to dev environment
  deploy-dev:
    name: "Deploy to Development"
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to development
        run: |
          echo "Deploying tenant-service to development environment"
          # Add your deployment logic here
          # cd apps/tenant-service/deploy
          # make deploy ENV=dev IMAGE_TAG=${{ github.sha }}
