name: 'Web Frontend CI'

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/web-frontend/**'
      - 'platform/ci-templates/frontend-ci.yaml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/web-frontend/**'
      - 'platform/ci-templates/frontend-ci.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-ci:
    name: 'React SPA CI/CD Pipeline'
    uses: ./.github/workflows/../../../platform/ci-templates/frontend-ci.yaml
    with:
      frontend_type: 'spa'
      service_path: 'apps/web-frontend'
      node_version: '18'
      deploy_target: 'vercel'  # Can be: vercel, s3-cloudfront, cdn
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CDN_DEPLOY_URL: ${{ secrets.CDN_DEPLOY_URL }}

  notify-success:
    needs: frontend-ci
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Notify deployment success
        run: |
          echo "🎉 Web Frontend deployment successful!"
          echo "📱 Preview URL: ${{ needs.frontend-ci.outputs.deployment-url }}"