apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
  - name: http
    port: 8005
    targetPort: 8005
    protocol: TCP
  type: ClusterIP