apiVersion: v1
kind: Service
metadata:
  name: realtime
  labels:
    app: realtime
spec:
  selector:
    app: realtime
  ports:
  - name: http
    port: 8004
    targetPort: 8004
    protocol: TCP
  type: ClusterIP