openapi: 3.0.3
info:
  title: Realtime Service
  description: WebSocket service with backpressure handling
  version: 1.0.0
  contact:
    name: Platform Team
    email: platform@company.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: http://localhost:8004
  description: Development server
- url: https://api.company.com
  description: Production server
security:
- BearerAuth: []
paths:
  /healthz:
    get:
      summary: Health check endpoint
      operationId: health_check
      tags:
      - Health
      security: []
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /v1/info:
    get:
      summary: Service information
      operationId: get_info
      tags:
      - Info
      security: []
      responses:
        '200':
          description: Service information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
  /v1/connections:
    get:
      summary: List active connections
      operationId: get__v1_connections
      tags:
      - Realtime
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/connections/{connection_id}/send:
    post:
      summary: Send message
      operationId: post__v1_connections_connection_id_send
      tags:
      - Realtime
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
  /v1/channels/{channel_id}/broadcast:
    post:
      summary: Broadcast to channel
      operationId: post__v1_channels_channel_id_broadcast
      tags:
      - Realtime
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
  /ws:
    get:
      summary: WebSocket endpoint
      operationId: get__ws
      tags:
      - Realtime
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    HealthResponse:
      type: object
      required:
      - status
      - timestamp
      properties:
        status:
          type: string
          enum:
          - healthy
          - degraded
          - unhealthy
        timestamp:
          type: string
          format: date-time
        version:
          type: string
        components:
          type: object
          additionalProperties:
            type: string
    InfoResponse:
      type: object
      required:
      - service
      - version
      properties:
        service:
          type: string
          example: realtime
        version:
          type: string
          example: 1.0.0
        description:
          type: string
          example: WebSocket service with backpressure handling
        build_time:
          type: string
          format: date-time
        commit_sha:
          type: string
    ErrorResponse:
      type: object
      required:
      - error
      - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
        trace_id:
          type: string
